In [58]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn import linear_model
from scipy import stats
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt


# Raw Data Loading
df = pd.read_csv('./data/Titanic/train.csv')
# display(df)

# 결측치 확인
# df.isnull().sum()
#Age            177
#Cabin          687
# Embarked         2

# 이상치 확인
# 성별 변경
df['Sex'] = np.array(df['Sex'] == 'female', dtype = np.int32) 
# sex_mapping = {'male' : 0 , 'female': 1}
# df['Sex'] = df['Sex'].map(sex_mapping) # python 의 map과 다른역할

# family 열 추가
df['Family'] = df['SibSp']|df['Parch']
# df['Family'] = df['SibSp']+df['Parch']

# Fare 는 그래도 사용

# Ticket 삭제
# P class 사용 삭제
# Suvived 종속변수

# Embarked 결측치 처리
df['Embarked'] = df['Embarked'].fillna('Q') # fillna 원하는 값으로 채움

# Age에 대한 결측치 처리
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Embarked 숫자로 처리
embarked_mapping = {'S' : 0 , 'C': 1, 'Q': 2}
df['Embarked'] = df['Embarked'].map(embarked_mapping)

# Age에 대해서 Binning 처리(Numerical value -> categorical value)
df.loc[df['Age'] < 8, 'Age'] = 0
df.loc[(df['Age'] >= 8) & (df['Age'] < 20), 'Age'] = 1
df.loc[(df['Age'] >= 20) & (df['Age'] < 65), 'Age'] = 2
df.loc[df['Age'] >= 65, 'Age'] = 4


df.drop(['PassengerId','Name','Ticket','Cabin','SibSp','Fare','Parch'],axis =1, inplace = True)
display(df)


# 데이터가 준비되었어요
# Tensorflow 를 이용해서 학습을 진행하고 Accuracy 를 구해보아요
# 891개의 데이터가 있어요 이걸 다 학습에 사용하면 안되요
# 7:3 비율로 데이터를 나누어서 학습과 정확도 측정에 사용해요!

     Survived  Pclass  Sex  Age  Embarked  Family
0           0       3    0  2.0         0       1
1           1       1    1  2.0         1       1
2           1       3    1  2.0         0       0
3           1       1    1  2.0         0       1
4           0       3    0  2.0         0       0
..        ...     ...  ...  ...       ...     ...
886         0       2    0  2.0         0       0
887         1       1    1  1.0         0       0
888         0       3    1  2.0         0       3
889         1       1    0  2.0         1       0
890         0       3    0  2.0         2       0

[891 rows x 6 columns]

In [63]:

# Tensorflow


zscore_threshold = 2.0

for col in df.columns:
    outlier = df[col][np.abs(stats.zscore(df[col])) > zscore_threshold]    
    df = df.loc[~df[col].isin(outlier)]
    

# Training Data Set
x_data = df.drop('Survived', axis=1, inplace=False).values
t_data = df['Survived'].values.reshape(-1,1)


# placeholder
X = tf.placeholder(shape=[None,5], dtype=tf.float32)  # 독립변수의 데이터를 받기위한 placeholder
T = tf.placeholder(shape=[None,1], dtype=tf.float32)  # 종속변수(label)의 데이터를 받기위한 placeholder

# Weight & bias
W = tf.Variable(tf.random.normal([5,1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

# hypothesis
logit = tf.matmul(X,W) + b
H = tf.sigmoid(logit)

# loss function
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=logit, labels=T))

# train
train = tf.train.GradientDescentOptimizer(learning_rate=1e-3).minimize(loss)


# session & 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# 학습
for step in range(30000):
    _, W_val, b_val, loss_val = sess.run([train, W, b, loss], 
                                         feed_dict={X:x_data, T:t_data})
    
    if step % 3000 == 0:
        print('W : {}, b : {}, loss : {}'.format(W_val, b_val, loss_val))

        
# 정확도(Accuracy)측정
predict = tf.cast(H >= 0.5, dtype=tf.float32)  # True -> 1.0, False -> 0
correct = tf.equal(predict,T)
accuracy = tf.reduce_mean(tf.cast(correct, dtype=tf.float32))

accuracy_val = sess.run(accuracy, feed_dict={X:x_data, T:t_data})
print('Accuracy : {}'.format(accuracy_val))
        
# prediction        
survice = np.array([[3, 0,2,0,1]])

result = sess.run(H,feed_dict={X:survice})
print('####### tensorflow 결과값 #########')
print('탑승정보 : {}, 생존확률 : {}'.format(survice,result))

W : [[ 0.97022253]
 [-0.1561186 ]
 [-0.37181994]
 [-0.13353974]
 [ 2.5207736 ]], b : [-0.01763167], loss : 1.5345916748046875
W : [[ 0.10459678]
 [ 0.09064544]
 [-0.73501825]
 [-0.07116231]
 [ 2.3395123 ]], b : [-0.1992303], loss : 0.670664370059967
W : [[-0.0717603 ]
 [ 0.36181536]
 [-0.5967815 ]
 [ 0.01994945]
 [ 2.1987367 ]], b : [-0.13011219], loss : 0.6183058023452759
W : [[-0.21023765]
 [ 0.59753305]
 [-0.48651513]
 [ 0.09281714]
 [ 2.0545845 ]], b : [-0.07497886], loss : 0.5795398950576782
W : [[-0.3200015 ]
 [ 0.80302566]
 [-0.4000654 ]
 [ 0.15087008]
 [ 1.9133995 ]], b : [-0.03175393], loss : 0.5505033135414124
W : [[-0.4068254 ]
 [ 0.9830145 ]
 [-0.3322401 ]
 [ 0.19728553]
 [ 1.7785581 ]], b : [0.00215872], loss : 0.5284544825553894
W : [[-0.47559237]
 [ 1.1415187 ]
 [-0.27881593]
 [ 0.2347405 ]
 [ 1.6516892 ]], b : [0.02887095], loss : 0.5114535689353943
W : [[-0.5303106 ]
 [ 1.2818842 ]
 [-0.23646104]
 [ 0.2653849 ]
 [ 1.5333538 ]], b : [0.0500485], loss : 0.4981405436992645
W : [[-0.5741711 ]
 [ 1.4068564 ]
 [-0.202598  ]
 [ 0.29088333]
 [ 1.4235437 ]], b : [0.06698], loss : 0.4875662624835968
W : [[-0.6096607 ]
 [ 1.5186728 ]
 [-0.17525464]
 [ 0.31249407]
 [ 1.3219554 ]], b : [0.08065169], loss : 0.4790623188018799
Accuracy : 0.7962003350257874
####### tensorflow 결과값 #########
탑승정보 : [[3 0 2 0 1]], 생존확률 : [[0.28865007]]

In [48]:
# Multinomial Classfication 
# BMI 지수에 대한 데이터를 가지고 학습 후 예측까지 진행해 볼꺼에요!!
# BMI 지수는 키와 몸무게를 가지고 저체중, 정상, 과체중, 비만을 판단하는 지수
# BMI = 자신의 몸무게(kg) / 키의 제곱(m)
# 18.5 이하면 저체중
# 18.5 ~23 정상
# 23 ~ 25 과체중
# 25이상 비만

# 우리가 하려는건 식이 아니라 BMI지수를 조사한 데이터가 있어요
# 이걸 학습해서 예측을 통해 나의 BMI지수를 알아보려고 합니다.
# 단, 제공하는 데이터는 4가지 분류가 아니라 3가지 분류로 나누어져 있어요!

import numpy as np
import pandas as pd
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_score, recall_score, accuracy_score


# Raw Data Loading
df = pd.read_csv('./data/bmi.csv', skiprows=3)

# 결측치부터 확인!
# df.isnull().sum()

# 이상치확인
# Z-score

zscore_threshold = 1.8

for col in df.columns:
    outlier = df[col][np.abs(stats.zscore(df[col])) > zscore_threshold]    
    df = df.loc[~df[col].isin(outlier)]
    
    
df.loc[np.abs(stats.zscore(df['height']))>=zscore_threshold,:] # height
df.loc[np.abs(stats.zscore(df['weight']))>=zscore_threshold,:] # weight
df.loc[np.abs(stats.zscore(df['label']))>=zscore_threshold,:] # label

# Data Split
# Train, Test 두 부분으로 분할
# 분리하는 비율은 7:3 으로 분리.
# 나중에 Train 부분은 K-fold cross validation을 진행할 꺼에요!

# 역슬레시로 칸넘기기
x_data_train, x_data_test, t_data_train, t_data_test =\
train_test_split(df[['height', 'weight']], df['label'], test_size=0.3, random_state=0) # 30% 테스트 사이즈

display(x_data_train)
display(x_data_test)

#Normalization
scaler = MinMaxScaler() # scaler 객체를 생성해요!
scaler.fit(x_data_train) # scaler 객체에 최대, 최소와 같은 정보가 들어가요!
x_data_train_norm = scaler.transform(x_data_train)
x_data_test_norm = scaler.transform(x_data_test)

del x_data_train #혼동을 방지하기 위해서 변수를 삭제
del x_data_test

# sklearn 구현은 매우매우 간단 !!
model = LogisticRegression()
model.fit(x_data_train_norm, t_data_train)

# 우리 model의 정확도를 측정해야 해요!
# cross validation
kfold = 10 
kfold_score = cross_val_score(model, x_data_train_norm, t_data_train, cv = kfold)
print('##########cross validation############')

print('score : {}'.format(kfold_score))
print('전체평균은 : {}'.format(kfold_score.mean()))

# 최종모델평가
predict_val = model.predict(x_data_test_norm) #테스트데이터로 예측값을 구해요!
acc = accuracy_score(predict_val, t_data_test)
print('우리 model의 최종 Accuracy : {}'.format(acc))

# Predict
height = 188
weight = 78
my_state = [[height, weight]]
my_state_val = model.predict(scaler.transform(my_state))

print(my_state_val)

       height  weight
8226      195      71
9398      120      74
11646     121      61
12193     158      36
18601     182      78
...       ...     ...
13123     137      60
19648     193      61
9845      146      79
10799     175      68
2732      180      57

[14000 rows x 2 columns]

       height  weight
19134     163      44
4981      153      66
16643     180      38
19117     171      61
5306      173      40
...       ...     ...
9532      196      47
9764      145      43
19241     178      55
3452      156      38
13373     172      70

[6000 rows x 2 columns]

##########cross validation############
score : [0.98       0.98642857 0.985      0.97642857 0.98642857 0.98428571
 0.98714286 0.97714286 0.97714286 0.98642857]
전체평균은 : 0.9826428571428572
우리 model의 최종 Accuracy : 0.9845
[1]